# ----------------------------------------------
# Setting
# ----------------------------------------------

/control/verbose 2
/tracking/verbose 1
/event/verbose 0
/gps/verbose 0

# ----------------------------------------------
# Particle
# ----------------------------------------------

# uniform irradiation
/gps/ang/type iso

# if you save conputational time
/gps/ang/maxtheta 90 deg
# direction of x axis
/gps/ang/rot1 0 0 1
# direction of xy plane
/gps/ang/rot2 0 1 0

/gps/pos/type Point
/gps/position -20 0 0 cm

/gps/particle gamma
/gps/ene/type Mono
/gps/ene/mono 0.662 MeV

# ----------------------------------------------
# run
# ----------------------------------------------

/run/beamOn 100000000
#/run/beamOn 100
